# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549612775);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549612895);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1550559829);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1549612655);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549613135);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549612535);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1549613255);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549613015);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 58);
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1549573200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1549612455);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549649852389");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549651674389");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549623789957");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549627389957");
user_pref("browser.search.countryCode", "KE");
user_pref("browser.search.region", "KE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20171116103757");
user_pref("browser.startup.homepage_override.buildID", "20171116103757");
user_pref("browser.startup.homepage_override.mstone", "57.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":12,\"newElementCount\":2}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20190208);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.ipc.processCount.web", 4);
user_pref("e10s.rollout.cohort", "multiBucket4");
user_pref("e10s.rollout.cohortSample", "0.817806");
user_pref("e10s.rollout.cohortSample.multi", "0.153680");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.cache.lastUpdate", 1549612778);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20171116103757");
user_pref("extensions.lastAppVersion", "57.0");
user_pref("extensions.lastPlatformVersion", "57.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.user_id", "69b84e27-89c9-435b-92c6-9452c257401b");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8dda6d9e-fb8a-4be7-8b2c-e3927c7c7ab8}\",\"addons\":{\"disable-crash-autosubmit@mozilla.org\":{\"version\":\"2.1\"},\"disable-js-shared-memory@mozilla.org\":{\"version\":\"2.0\"},\"disable-media-wmf-nv12@mozilla.org\":{\"version\":\"1.1\"},\"telemetry-coverage-bug1487578@mozilla.org\":{\"version\":\"8.0\"}}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"b18d04f4-0523-4c9f-89b3-a70599662321\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1549621131);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1549612783);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20171116103757");
user_pref("media.gmp-manager.lastCheck", 1549612852);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1549621131);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1549612855);
user_pref("services.blocklist.clock_skew_seconds", 41);
user_pref("services.blocklist.gfx.checked", 1549612855);
user_pref("services.blocklist.last_etag", "\"1549541801862\"");
user_pref("services.blocklist.last_update_seconds", 1549612855);
user_pref("services.blocklist.onecrl.checked", 1549612855);
user_pref("services.blocklist.pinning.checked", 1549612855);
user_pref("services.blocklist.plugins.checked", 1549612855);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1549621131);
user_pref("toolkit.startup.last_success", 1550577710);
user_pref("toolkit.telemetry.cachedClientID", "05e17225-93c0-413e-b432-b995f94c260c");
user_pref("toolkit.telemetry.previousBuildID", "20171116103757");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
